name = "butterfly_db"

[network]
port = 4343
bind_address = "127.0.0.1"

[resource]
# megabytes
max_disk_io_rate=10
max_cpu_percent=50
max_concurrent_connection=100
enable_rate_limiting=true
max_ram_usage=10000

[replication]
mode=""
write_quorum=2
auto_failover_enabled=true
max_read_replicas=10
max_write_replicas=4
